import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Duc toan',
      email: 'ductoan20102000@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Toan user',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Fashion shoes 0',
      category: 'Man',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Vans',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 1',
      category: 'Woman',
      image: '/images/p2.jpg',
      price: 148,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 2',
      category: 'Man',
      image: '/images/p3.jpg',
      price: 99,
      countInStock: 16,
      brand: 'Vans',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 3',
      category: 'Man',
      image: '/images/p4.jpg',
      price: 199,
      countInStock: 1,
      brand: 'Vans',
      rating: 5.0,
      numReviews: 58,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 4',
      category: 'Man',
      image: '/images/p5.jpg',
      price: 450,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 2,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 5',
      category: 'Man',
      image: '/images/p6.jpg',
      price: 251,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 55,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 6',
      category: 'Woman',
      image: '/images/p7.jpg',
      price: 456,
      countInStock: 49,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 7',
      category: 'Man',
      image: '/images/p8.jpg',
      price: 148,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 6,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 8',
      category: 'Woman',
      image: '/images/p9.jpg',
      price: 423,
      countInStock: 99,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 0,
      description: 'high quality products',
    },
    {
      name: 'Fashion shoes 9',
      category: 'Man',
      image: '/images/p10.jpg',
      price: 142,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality products',
    },
  ],
};

export default data;
