const data = {
  products: [
    {
      _id: '1',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Vans',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality products',
    },
    {
      _id: '2',
      name: 'Fashion shoes',
      category: 'Woman',
      image: '/images/p2.jpg',
      price: 148,
      countInStock: 25,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      _id: '3',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p3.jpg',
      price: 99,
      countInStock: 16,
      brand: 'Vans',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      _id: '4',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p4.jpg',
      price: 199,
      countInStock: 1,
      brand: 'Vans',
      rating: 5.0,
      numReviews: 58,
      description: 'high quality products',
    },
    {
      _id: '5',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p5.jpg',
      price: 450,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 2,
      description: 'high quality products',
    },
    {
      _id: '6',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p6.jpg',
      price: 251,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 55,
      description: 'high quality products',
    },
    {
      _id: '7',
      name: 'Fashion shoes',
      category: 'Woman',
      image: '/images/p7.jpg',
      price: 456,
      countInStock: 49,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 15,
      description: 'high quality products',
    },
    {
      _id: '8',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p8.jpg',
      price: 148,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 6,
      description: 'high quality products',
    },
    {
      _id: '9',
      name: 'Fashion shoes',
      category: 'Woman',
      image: '/images/p9.jpg',
      price: 423,
      countInStock: 99,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 0,
      description: 'high quality products',
    },
    {
      _id: '10',
      name: 'Fashion shoes',
      category: 'Man',
      image: '/images/p10.jpg',
      price: 142,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality products',
    },
  ],
};

export default data;